//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.19 at 05:01:46 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://buildingsmart-tech.org/mvd/XML/1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.rwth_aachen.dc.mvdxml.xsd1_1;
