# we are extending everything from tomcat:8.0 image ...
FROM tomcat:9.0
MAINTAINER Jyrki Oraskari
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY mvdXMLCheckerUserInterface-1.4.war /usr/local/tomcat/webapps/ROOT.war


